### ISSUE TITLE
[AC:SLPortable] Game occasionally crashes when attempting to view a replay

### ISSUE THREAD

**Issue by onionpowder2** [VanLaser/analog-controls-for-armored-core-ps2#1]
When I have the current analog patch for Silent Line Portable enabled, the game occasionally crashes when attempting to view replays after arena matches. I also had one crash when attempting to enter an arena match, but I could not replicate that after the fact. (Edit: replicated this crash, but the error is exactly the same as pictured) Obviously replays aren't intended to work, but I don't think a game crash is intended behavior, especially when it only sometimes occurs. Attached is a picture of the moment the game crashed after an arena match (versus Mobius, if it's relevant).

(Edit 2: I've also experienced identical crashes attempting to start missions and AC tests, so it isn't explicitly related to the arena.)

Played on PPSSPP v1.16.6

![image](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/108959396/cb95216e-22fa-48ce-b20e-8e7975c60ef8)

**Comment by VanLaser** [comment]
Thanks for the description of the situation, the picture and the feedback in general!, that can be useful. I just need to replicate the crashes on my side.

If you want to test with modified ISOs instead of cwcheats, to see if the patched ISO is more stable, read below (if no, it's perfectly fine too):

I uploaded PPF patches for both PSP games, these are meant to be applied on the decrypted EBOOT.BIN files from each game, NOT on the ISOs. Procedure:

1) PPSSPP can be configured to generate a decrypted EBOOT.BIN (or you can extract the EBOOT.BIN from the ISO with 7zip, then find some "pspdecrypt" tool and use that on the .BIN file)  
2) then you'd need PPF-O-MATIC 3.0 or other compatible tool to apply the PPF patch on that decrypted EBOOT.BIN.   
3) Finally you'd also need UMDGen or a similar tool to insert the new, patched EBOOT.BIN inside the original ISO in place of the old EBOOT.BIN.

This convoluted method is necessary since I can't simply make a PPF patch on the ISO directly - the original EBOOT.BIN file is encrypted, and patching that would create a file that somehow still contains information for the whole executable, instead of just a difference - and that can be legally problematic.

**Comment by VanLaser** [comment]
Ok, did some tests with (1) cwcheat method and (2) patched ISO -  I managed to crash once in the arena replay with the cwcheat, and the boost flame was not visible. With method (2), the booster flame IS visible (and no crashes after 2 arena replays and one mission), so this already should prove the cwcheat method DOES something unintended since it affects the graphical parts of the game (which the mod doesn't touch). Which means the 2nd method (patched ISO through the convoluted method described above) has chances to be OK.

**Comment by Victor792019** [comment]
Well, after testing the .ppf patches in modified SLp and 3p .isos, with the cheats off, dual-analog and purging were working. Plus, after some runs in the arenas, test 2 and the final missions of each game, no crashes were triggered, with "fast memory" checked on the emulator for both games, along with the booster flames being present in SLp.
Used 2 ACs with left, right and back weapons plus extensions, if it means something.
Played on PPSSPP v.1.16.6-283 dev build
![NPUH10023_00003](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/139256866/1478d0ba-ff49-4148-b804-4a8028370cd1)
![NPUH10025_00002](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/139256866/ce4a3485-9040-4d3f-b727-a83f64e64e9b)

**Comment by VanLaser** [comment]
Thanks a lot for the tests and the feedback! I'll let this issue (and the booster flame one) opened a little longer to see if other people have positive/negative feedback to share.

**Comment by onionpowder2** [comment]
Just tested the PPF patch, the booster effects are back and I didn't see any crashes during my testing, even in spots where the game would normally crash more often than not (the mission "Qualification Exam" was guilty of crashing VERY often for me) with the cwcheats.

**Comment by VanLaser** [comment]
Thanks a lot for the detailed testing! :)

**Comment by VanLaser** [comment]
Closing this and the booster flame issue (the PPF solution seems to be working), in the next version of these patches I will probably remove the _cwcheat_ version completely.
