### ISSUE TITLE
Analog Patch not working for AC1 with DuckStation [incompatible emulator save state]

### ISSUE THREAD

**Issue by Xecxciic** [VanLaser/analog-controls-for-armored-core-ps2#7]
I've set DuckStation to apply image patches, renamed the correct ppf file for my version of the game (Reprint 01323) and ensured the bin, cue, and ppf are in their own folder, the game does not work on analog mode, and hangs when trying to load ac test

**Comment by VanLaser** [comment]
- Make sure you have the "clean" game image, no other patches applied to it. The CRC of the AC1 USA reprint ".bin" file should be: 32d117f3
 - Try to explicitly apply the PPF patch, using PPF-0-Matic v3, and see if Duckstation loads that instead

**Comment by Xecxciic** [comment]
The CRC is exactly that, and I've tried applying the patch with ppf-o-matic and the effects are the same.

**Comment by VanLaser** [comment]
Something else has to be fishy though, since that patched image was tested on Windows and Linux PCs, and even on a handheld with ArkOS Linux. And I got reports from other people that it works on Duckstation + Android based handhelds too. Try a clean,  separate, new version of Duckstation maybe? (if there's a 'portable' version, you won't need to install it, you can have it alongside your current Duckstation, but in a different folder). With a recent US PS1 BIOS, if possible. I assume you're on Windows, since you don't mention it.

**Comment by Xecxciic** [comment]
My install of DuckStation was already fresh, I downloaded it specifically for playing Armored Core and haven't changed any settings other than some video scaling setting and the ones listed for this patch. I'm not sure what you mean by "recent" bios, I went and found what I believed to be the most recently released ps1 bios, SCPH-101 as well as a differently sourced image and the results are the same. Yes I am on windows, and not very experienced with tech support so if there's any other information you need to help zero in on what the problem is ask and I'll provide.

**Comment by VanLaser** [comment]
If you can, search on the web for the prepatched cd image (cdromance has it, search for "true analogs"), then: 1) test that, and 2) compare it with your patched file. It may be that if it's not the wrong ".bin" and Duckstation is fresh, what's left is maybe you used the wrong PPF patch.

**Comment by Xecxciic** [comment]
I wasn't using the wrong patch, and the prepatched rom didn't help either. The actual issue is a bit more foolish, I was being impatient and just loading a save state on the menus from the unpatched version after opening the game, which seems to have been the source of the issue. Thanks for the troubleshooting, but can't fix stupid!

**Comment by VanLaser** [comment]
Glad you found the issue, and don't be too hard on yourself!

PS1 has limited RAM, so games had to swap code in and out all the time, that's why it was "kinda" working for you until you tried to do the AC test. You were basically mixing patched code with unpatched code there, due to what Duckstation was itself loading from the save state.
